<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
$helper  = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php $options = $block->decorateArray($block->getOptions()); ?>
<?php if ($product->isSaleable()): ?>
    <?php if (count($options)): ?>
        <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "priceBundle": {
                "optionConfig": <?php /* @escapeNotVerified */
            echo $block->getJsonConfig() ?>,
                "controlContainer": ".field.option"
            }
        }
    }

        </script>
        <script>
            var bundleConfig = <?php echo $block->getJsonConfig()?>
        </script>
        <fieldset class="fieldset fieldset-bundle-options">
            <?php foreach ($options as $option): ?>
                <?php if (!$option->getSelections()): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <div data-mage-init='{
                    "collapsible": {
                        "collapsible": true,
                        "openedState": "active",
                        "active": true,
                        "animate": { "duration": 1000, "easing": "easeOutCubic" }
                    }}'>
                    <div data-role="title">
                        <?php echo $block->escapeHtml($option->getTitle()) ?>
                    </div>
                    <div data-role="content">
                        <?php echo $block->getOptionHtml($option) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </fieldset>
    <?php else: ?>
        <p class="empty"><?php /* @escapeNotVerified */
            echo __('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif; ?>
